appveyor: don't use pypy temporarily due to choco-bitbucket trouble
```
python.pypy v7.3.1 [Approved]
python.pypy package files install completed. Performing other installation steps.
Attempt to get headers for https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.3.1-win32.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.3.1-win32.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
  Downloading python.pypy
    from 'https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.3.1-win32.zip'
    ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.3.1-win32.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
    This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
    The install of python.pypy was NOT successful.
    Error while running 'C:\ProgramData\chocolatey\lib\python.pypy\tools\chocolateyinstall.ps1'.
     See log for details.
     Chocolatey installed 1/2 packages. 1 packages failed.
      See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
      Failures
       - python.pypy (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\python.pypy\tools\chocolateyinstall.ps1'.
        See log for details.
        Command exited with code 404
```